language: go

go:
  - 1.x

install:
  - export GO111MODULE=on
  - go get -t ./...

script:
  - echo $GO111MODULE
  - make test

after_success:
  - $GOPATH/bin/goveralls -coverprofile=profile.cov -service=travis-ci

notifications:
  email: false
