language: go
go: stable

stages:
  - lint
  - build
  - test

jobs:
  include:
    - stage: lint
      name: go fmt
      script: make test_fmt
    - name: golint
      script: make test_lint

    - stage: build
      name: go build
      script: go build ./...
    - name: go build -tags vartime
      script: go build -tags vartime ./...

    - stage: test
      name: go test
      script: ./coveralls.sh -race
    - name: go test -tags vartime
      script: ./coveralls.sh -race -tags vartime
      after_success: $GOPATH/bin/goveralls -coverprofile=profile.cov -service=travis-ci

cache:
  directories: $GOPATH/src

notifications:
  email: false
